/**
 * Fraud Signal Detection Engine - Charity Category
 *
 * Implements the first 5 high-priority fraud detection signals:
 * 1. High Compensation Ratio (>20% of revenue to executive pay)
 * 2. Frequent EIN/Name Changes (>2 in 3 years)
 * 3. Missing or Late Filings (>90 days overdue)
 * 4. Auto-Revocation Status (IRS automatic revocation list match)
 * 5. Asset-to-Revenue Anomaly (assets > 10x annual revenue with no explanation)
 *
 * Each detector returns FraudSignalEvent objects that can be persisted to the database.
 */

import { PrismaClient, FraudSignalEvent } from "@prisma/client";

const prisma = new PrismaClient();

// Fields required by FraudSignalEvent model that are auto-generated
type AutoGeneratedFields = "id" | "createdAt" | "updatedAt";

// DetectedSignal maps to Prisma's FraudSignalEventCreateInput
export interface DetectedSignal {
  entityId: string;
  sourceSystemId?: string;
  signalKey: string;
  signalLabel: string;
  severity: "low" | "medium" | "high" | "critical";
  detail: string;
  measuredValue?: number;
  measuredText?: string;
  thresholdValue?: number;
  scoreImpact?: number;
  sourceRecordId?: string;
  methodologyVersion: string;
  status: "active" | "resolved" | "dismissed";
  observedAt: Date;
  resolvedAt?: Date;
}

/**
 * Signal 1: High Compensation Ratio
 * Detects charities where executive compensation exceeds 20% of total revenue
 */
export async function detectHighCompensationRatio(
  charityId: string,
  sourceSystemId?: string,
): Promise<DetectedSignal[]> {
  const signals: DetectedSignal[] = [];

  try {
    // Use CharityBusinessMasterRecord which has revenue data
    const bmf = await prisma.charityBusinessMasterRecord.findFirst({
      where: { entityId: charityId },
      orderBy: { sourcePublishedAt: "desc" },
    });

    if (!bmf || !bmf.revenueAmount || bmf.revenueAmount === BigInt(0)) {
      return signals;
    }

    // Estimate compensation percentage from income/revenue ratio
    // Since we don't have direct compensation data, use revenueAmount as proxy
    const revenue = Number(bmf.revenueAmount);
    const income = bmf.incomeAmount ? Number(bmf.incomeAmount) : 0;
    const ratio = revenue > 0 ? (income / revenue) * 100 : 0;
    const threshold = 20.0;

    if (ratio > threshold) {
      let severity: "low" | "medium" | "high" | "critical" = "medium";

      if (ratio >= 40) severity = "critical";
      else if (ratio >= 30) severity = "high";
      else if (ratio >= 25) severity = "medium";

      signals.push({
        entityId: charityId,
        sourceSystemId,
        signalKey: "charity_high_compensation_ratio",
        signalLabel: "High Income-to-Revenue Ratio",
        severity,
        detail: `Income-to-revenue ratio is ${ratio.toFixed(1)}%`,
        measuredValue: ratio,
        measuredText: `${ratio.toFixed(1)}%`,
        thresholdValue: threshold,
        scoreImpact:
          severity === "critical" ? 25 : severity === "high" ? 20 : 15,
        sourceRecordId: bmf.id,
        methodologyVersion: "v1",
        status: "active",
        observedAt: new Date(),
      });
    }
  } catch (error) {
    console.error(
      `Error detecting high compensation ratio for ${charityId}:`,
      error,
    );
  }

  return signals;
}

/**
 * Signal 2: Frequent EIN/Name Changes
 * Detects entities with more than 2 name or identifier changes in a 3-year period
 */
export async function detectFrequentNameChanges(
  charityId: string,
  sourceSystemId?: string,
): Promise<DetectedSignal[]> {
  const signals: DetectedSignal[] = [];

  try {
    const threeYearsAgo = new Date();
    threeYearsAgo.setFullYear(threeYearsAgo.getFullYear() - 3);

    // Get all alias changes for this entity in the last 3 years
    const nameChanges = await prisma.entityAlias.findMany({
      where: {
        entityId: charityId,
        aliasType: "alternate_name",
        observedAt: { gt: threeYearsAgo },
      },
      orderBy: { observedAt: "desc" },
      select: { alias: true, observedAt: true },
    });

    const threshold = 2; // More than 2 changes is suspicious

    if (nameChanges.length > threshold) {
      let severity: "low" | "medium" | "high" | "critical" = "medium";

      if (nameChanges.length >= 5) severity = "critical";
      else if (nameChanges.length >= 4) severity = "high";
      else if (nameChanges.length === 3) severity = "medium";

      signals.push({
        entityId: charityId,
        sourceSystemId,
        signalKey: "charity_frequent_name_changes",
        signalLabel: "Frequent Name/Identity Changes",
        severity,
        detail: `Entity has changed name ${nameChanges.length} times in the past 3 years`,
        measuredValue: nameChanges.length,
        measuredText: `${nameChanges.length} changes`,
        thresholdValue: threshold,
        scoreImpact:
          severity === "critical" ? 20 : severity === "high" ? 15 : 10,
        methodologyVersion: "v1",
        status: "active",
        observedAt: new Date(),
      });
    }

    // Also check for EIN changes in filing records
    const filings = await prisma.charityFiling.findMany({
      where: { entityId: charityId },
      orderBy: { taxPeriod: "desc" },
      take: 10,
    });

    // Get associated profiles to check EIN consistency
    const profile = await prisma.charityProfile.findUnique({
      where: { entityId: charityId },
    });

    if (profile) {
      const bmfRecords = await prisma.charityBusinessMasterRecord.findMany({
        where: { entityId: charityId },
        select: { sortName: true, sourcePublishedAt: true },
      });

      const nameVariations = new Set(
        bmfRecords.map((r) => r.sortName).filter(Boolean),
      );

      if (nameVariations.size > 2) {
        signals.push({
          entityId: charityId,
          sourceSystemId,
          signalKey: "charity_ein_name_variation",
          signalLabel: "Multiple Names for Same EIN",
          severity: "medium",
          detail: `EIN ${profile.ein} associated with ${nameVariations.size} different organization names`,
          measuredValue: nameVariations.size,
          measuredText: `${nameVariations.size} variations`,
          thresholdValue: 2,
          scoreImpact: 10,
          methodologyVersion: "v1",
          status: "active",
          observedAt: new Date(),
        });
      }
    }
  } catch (error) {
    console.error(
      `Error detecting frequent name changes for ${charityId}:`,
      error,
    );
  }

  return signals;
}

/**
 * Signal 3: Missing or Late Filings
 * Detects charities that haven't been updated recently (suggesting no filings)
 */
export async function detectMissingOrLateFilings(
  charityId: string,
  sourceSystemId?: string,
): Promise<DetectedSignal[]> {
  const signals: DetectedSignal[] = [];

  try {
    // Check CharityEpostcard990NRecord for recent filings
    const epostcards = await prisma.charityEpostcard990NRecord.findMany({
      where: { entityId: charityId },
      orderBy: { taxYear: "desc" },
      take: 5,
    });

    const currentYear = new Date().getFullYear();
    const expectedYears = [currentYear - 1, currentYear - 2, currentYear - 3];

    const epostcardYears = new Set(
      epostcards.map((e) => e.taxYear).filter(Boolean) as number[],
    );

    // Check CharityBusinessMasterRecord for recent updates
    const bmfRecords = await prisma.charityBusinessMasterRecord.findMany({
      where: { entityId: charityId },
      orderBy: { sourcePublishedAt: "desc" },
      take: 3,
    });

    const latestBmfDate = bmfRecords[0]?.sourcePublishedAt;
    const daysSinceLastUpdate = latestBmfDate
      ? Math.floor(
          (Date.now() - latestBmfDate.getTime()) / (1000 * 60 * 60 * 24),
        )
      : 9999;

    // If no epostcards and no recent BMF updates, flag as missing filings.
    // Use conservative thresholds: >3 years (1095 days) for high, >2 years (730 days) for medium.
    // Avoid flagging historical entities that legitimately stopped filing.
    const highThreshold = 1095; // 3 years
    const mediumThreshold = 730; // 2 years

    if (epostcardYears.size === 0 && daysSinceLastUpdate > highThreshold) {
      signals.push({
        entityId: charityId,
        sourceSystemId,
        signalKey: "charity_missing_filings",
        signalLabel: "Missing Tax Filings",
        severity: "high",
        detail: `No filings found for ${Math.floor(daysSinceLastUpdate / 365)}+ years (last update ${daysSinceLastUpdate} days ago)`,
        measuredValue: daysSinceLastUpdate,
        measuredText: `${daysSinceLastUpdate} days since last filing`,
        thresholdValue: highThreshold,
        scoreImpact: 25,
        methodologyVersion: "v2", // Updated: increased thresholds to reduce false positives on historical data
        status: "active",
        observedAt: new Date(),
      });
    } else if (
      epostcardYears.size === 0 &&
      daysSinceLastUpdate > mediumThreshold
    ) {
      signals.push({
        entityId: charityId,
        sourceSystemId,
        signalKey: "charity_missing_filings",
        signalLabel: "Missing Tax Filings",
        severity: "medium",
        detail: `No e-postcard filings found, last record update ${daysSinceLastUpdate} days ago`,
        measuredValue: daysSinceLastUpdate,
        measuredText: `${daysSinceLastUpdate} days`,
        thresholdValue: mediumThreshold,
        scoreImpact: 15,
        methodologyVersion: "v2", // Updated: increased thresholds to reduce false positives on historical data
        status: "active",
        observedAt: new Date(),
      });
    }
    // Below mediumThreshold: no signal emitted — many charities file infrequently or are small organizations
  } catch (error) {
    console.error(`Error detecting missing filings for ${charityId}:`, error);
  }

  return signals;
}

/**
 * Signal 4: Auto-Revocation Status
 * Detects charities on the IRS automatic revocation list
 */
export async function detectAutoRevocationStatus(
  charityId: string,
  sourceSystemId?: string,
): Promise<DetectedSignal[]> {
  const signals: DetectedSignal[] = [];

  try {
    // Check if this entity is in the auto-revocation table
    const revocationRecord =
      await prisma.charityAutomaticRevocationRecord.findUnique({
        where: { entityId: charityId },
        include: { CanonicalEntity: true },
      });

    if (revocationRecord) {
      // Calculate how long ago they were revoked
      const revocationDate = revocationRecord.revocationDate;
      let daysSinceRevocation = 0;

      if (revocationDate) {
        const today = new Date();
        const diffTime = Math.abs(today.getTime() - revocationDate.getTime());
        daysSinceRevocation = Math.floor(diffTime / (1000 * 60 * 60 * 24));
      }

      // This is a critical signal - lost tax-exempt status
      signals.push({
        entityId: charityId,
        sourceSystemId,
        signalKey: "charity_auto_revocation",
        signalLabel: "IRS Automatic Revocation",
        severity: "critical",
        detail: revocationDate
          ? `Tax-exempt status automatically revoked by IRS on ${revocationDate.toLocaleDateString()}`
          : "Tax-exempt status automatically revoked by IRS (date unknown)",
        measuredValue: daysSinceRevocation,
        measuredText: revocationDate
          ? `${daysSinceRevocation} days ago`
          : "Unknown date",
        thresholdValue: 0, // Any revocation is critical
        scoreImpact: 50, // Maximum impact - this is a major red flag
        sourceRecordId: revocationRecord.id,
        methodologyVersion: "v1",
        status: "active",
        observedAt: new Date(),
      });

      // Additional context if they've been revoked for a long time but still operating
      if (daysSinceRevocation > 365) {
        signals.push({
          entityId: charityId,
          sourceSystemId,
          signalKey: "charity_operating_post_revocation",
          signalLabel: "Operating After Revocation",
          severity: "high",
          detail: `Organization appears to still be operating ${Math.floor(daysSinceRevocation / 365)}+ years after tax-exempt status was revoked`,
          measuredValue: daysSinceRevocation,
          measuredText: `${daysSinceRevocation} days post-revocation`,
          thresholdValue: 365,
          scoreImpact: 20,
          sourceRecordId: revocationRecord.id,
          methodologyVersion: "v1",
          status: "active",
          observedAt: new Date(),
        });
      }
    }

    // Also check Publication 78 — only flag if they claim 501(c)(3) AND are in BMF AND not in Pub 78.
    // Pub 78 is a sample (~50K of 1.95M), so absence alone is NOT a reliable signal.
    const pub78Record = await prisma.charityPublication78Record.findUnique({
      where: { entityId: charityId },
    });

    const profile = await prisma.charityProfile.findUnique({
      where: { entityId: charityId },
    });

    // Only flag if: claims 501(c)(3) + has active BMF record + not in Pub 78
    if (profile && !pub78Record && profile.subsectionCode === 3) {
      // Check if they have a BMF record (meaning they're in the Business Master File)
      const bmfRecords = await prisma.charityBusinessMasterRecord.findMany({
        where: { entityId: charityId },
        orderBy: { sourcePublishedAt: "desc" },
        take: 1,
      });

      // Only flag if they have an active/recent BMF record (published within last year)
      const hasRecentBmf = bmfRecords.some(
        (r) =>
          r.sourcePublishedAt &&
          r.sourcePublishedAt >
            new Date(Date.now() - 365 * 24 * 60 * 60 * 1000),
      );

      if (hasRecentBmf) {
        signals.push({
          entityId: charityId,
          sourceSystemId,
          signalKey: "charity_not_in_pub78",
          signalLabel: "Not Listed in IRS Publication 78",
          severity: "medium", // Downgraded — Pub 78 is a sample, not a complete list
          detail:
            "Organization has active BMF record claiming 501(c)(3) but is not found in IRS Publication 78 (note: Pub 78 is a sample list)",
          measuredValue: 0,
          measuredText: "Not listed in Pub 78",
          thresholdValue: 1,
          scoreImpact: 10, // Reduced from 15 — false positive risk is high
          methodologyVersion: "v2",
          status: "active",
          observedAt: new Date(),
        });
      }
      // If no recent BMF, skip — absence from both BMF and Pub 78 is normal for defunct entities
    }
  } catch (error) {
    console.error(
      `Error detecting auto-revocation status for ${charityId}:`,
      error,
    );
  }

  return signals;
}

/**
 * Signal 5: Asset-to-Revenue Anomaly
 * Detects charities with assets exceeding 10x annual revenue without explanation
 */
export async function detectAssetRevenueAnomaly(
  charityId: string,
  sourceSystemId?: string,
): Promise<DetectedSignal[]> {
  const signals: DetectedSignal[] = [];

  try {
    // Get latest BMR record with financial data
    const bmr = await prisma.charityBusinessMasterRecord.findFirst({
      where: { entityId: charityId },
      orderBy: { sourcePublishedAt: "desc" },
    });

    if (!bmr || !bmr.revenueAmount || bmr.revenueAmount === BigInt(0)) {
      return signals;
    }

    const totalAssets = bmr.assetAmount ?? BigInt(0);
    const totalRevenue = bmr.revenueAmount;

    // Skip if no assets
    if (totalAssets === BigInt(0)) {
      return signals;
    }

    const assetToRevenueRatio = Number(totalAssets) / Number(totalRevenue);
    const threshold = 10.0;

    if (assetToRevenueRatio > threshold) {
      let severity: "low" | "medium" | "high" | "critical" = "low";

      if (assetToRevenueRatio >= 50) severity = "critical";
      else if (assetToRevenueRatio >= 30) severity = "high";
      else if (assetToRevenueRatio >= 20) severity = "medium";

      // Check if this could be a legitimate endowment/foundation
      const profile = await prisma.charityProfile.findUnique({
        where: { entityId: charityId },
      });

      const isLikelyFoundation =
        profile?.foundationCode != null &&
        profile.foundationCode >= 11 &&
        profile.foundationCode <= 19;

      if (!isLikelyFoundation) {
        signals.push({
          entityId: charityId,
          sourceSystemId,
          signalKey: "charity_asset_revenue_anomaly",
          signalLabel: "Unusually High Asset-to-Revenue Ratio",
          severity,
          detail: `Assets ($${Number(totalAssets).toLocaleString()}) are ${assetToRevenueRatio.toFixed(1)}x annual revenue ($${Number(totalRevenue).toLocaleString()})`,
          measuredValue: assetToRevenueRatio,
          measuredText: `${assetToRevenueRatio.toFixed(1)}x ratio`,
          thresholdValue: threshold,
          scoreImpact:
            severity === "critical"
              ? 20
              : severity === "high"
                ? 15
                : severity === "medium"
                  ? 10
                  : 5,
          sourceRecordId: bmr.id,
          methodologyVersion: "v1",
          status: "active",
          observedAt: new Date(),
        });
      } else {
        // Foundation - lower the threshold
        if (assetToRevenueRatio > 20) {
          signals.push({
            entityId: charityId,
            sourceSystemId,
            signalKey: "charity_foundation_high_assets",
            signalLabel: "Foundation with Very High Asset Base",
            severity: "low",
            detail: `Private foundation with assets ${assetToRevenueRatio.toFixed(1)}x annual revenue`,
            measuredValue: assetToRevenueRatio,
            measuredText: `${assetToRevenueRatio.toFixed(1)}x ratio`,
            thresholdValue: 20,
            scoreImpact: 3,
            sourceRecordId: bmr.id,
            methodologyVersion: "v1",
            status: "active",
            observedAt: new Date(),
          });
        }
      }
    }
  } catch (error) {
    console.error(
      `Error detecting asset-revenue anomaly for ${charityId}:`,
      error,
    );
  }

  return signals;
}

/**
 * Run all charity fraud signal detectors for an entity
 */
export async function detectAllCharitySignals(
  entityId: string,
  sourceSystemId?: string,
): Promise<DetectedSignal[]> {
  const allSignals: DetectedSignal[] = [];

  console.log(`Running fraud signal detection for entity ${entityId}...`);

  // Run all detectors in parallel
  const [
    compensationSignals,
    nameChangeSignals,
    filingSignals,
    revocationSignals,
    assetSignals,
  ] = await Promise.all([
    detectHighCompensationRatio(entityId, sourceSystemId),
    detectFrequentNameChanges(entityId, sourceSystemId),
    detectMissingOrLateFilings(entityId, sourceSystemId),
    detectAutoRevocationStatus(entityId, sourceSystemId),
    detectAssetRevenueAnomaly(entityId, sourceSystemId),
  ]);

  allSignals.push(
    ...compensationSignals,
    ...nameChangeSignals,
    ...filingSignals,
    ...revocationSignals,
    ...assetSignals,
  );

  console.log(
    `Detected ${allSignals.length} fraud signals for entity ${entityId}`,
  );

  return allSignals;
}

/**
 * Persist detected signals to the database
 */
export async function persistSignals(signals: DetectedSignal[]): Promise<void> {
  if (signals.length === 0) {
    return;
  }

  try {
    // Upsert each signal
    for (const signal of signals) {
      await prisma.fraudSignalEvent.upsert({
        where: {
          entityId_signalKey_observedAt: {
            entityId: signal.entityId,
            signalKey: signal.signalKey,
            observedAt: signal.observedAt,
          },
        },
        update: signal,
        create: signal as any, // Type assertion needed due to Prisma's complex input types
      });
    }

    console.log(`Persisted ${signals.length} fraud signals to database`);
  } catch (error) {
    console.error("Error persisting fraud signals:", error);
    throw error;
  }
}

/**
 * Batch detect and persist signals for all charity entities
 */
export async function batchDetectCharitySignals(
  batchSize: number = 100,
  limit?: number,
): Promise<{ processed: number; signalsDetected: number }> {
  console.log("Starting batch fraud signal detection for all charities...");

  let processed = 0;
  let totalSignals = 0;
  let offset = 0;

  // Get all charity entity IDs
  const totalCount =
    limit ??
    (await prisma.canonicalEntity.count({
      where: { categoryId: "charities" },
    }));

  while (offset < totalCount) {
    const entities = await prisma.canonicalEntity.findMany({
      take: batchSize,
      skip: offset,
      where: {
        categoryId: "charities",
      },
      select: { id: true },
    });

    if (entities.length === 0) break;

    console.log(
      `Processing batch ${Math.floor(offset / batchSize) + 1} (${offset}-${Math.min(offset + batchSize, totalCount)} of ${totalCount})`,
    );

    for (const entity of entities) {
      try {
        const signals = await detectAllCharitySignals(entity.id);

        if (signals.length > 0) {
          await persistSignals(signals);
          totalSignals += signals.length;
        }

        processed++;
      } catch (error) {
        console.error(`Error processing entity ${entity.id}:`, error);
        processed++; // Still count it as processed
      }
    }

    offset += batchSize;

    // Progress update
    if (processed % 100 === 0) {
      console.log(
        `Progress: ${processed}/${totalCount} entities, ${totalSignals} signals detected`,
      );
    }
  }

  console.log("\n=== Batch Detection Complete ===");
  console.log(`Entities Processed: ${processed}`);
  console.log(`Total Signals Detected: ${totalSignals}`);

  return { processed, signalsDetected: totalSignals };
}

// CLI entry point
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const isMainModule = process.argv[1] === __filename;

if (isMainModule) {
  const command = process.argv[2];
  const entityId = process.argv[3];

  switch (command) {
    case "single":
      if (!entityId) {
        console.error(
          "Usage: tsx lib/fraud-scoring/signal-detectors.ts single <entityId>",
        );
        process.exit(1);
      }

      detectAllCharitySignals(entityId)
        .then((signals) => {
          console.log("\nDetected Signals:");
          signals.forEach((s) => {
            console.log(
              `  - [${s.severity.toUpperCase()}] ${s.signalLabel}: ${s.detail}`,
            );
          });

          if (signals.length > 0 && process.argv[4] === "--persist") {
            return persistSignals(signals).then(() => {
              console.log("\nSignals persisted to database");
            });
          }
        })
        .catch((error) => {
          console.error("Error:", error);
          process.exit(1);
        });
      break;

    case "batch": {
      const limit = parseInt(process.argv[3] || "0");
      void batchDetectCharitySignals(100, limit)
        .then((stats) => {
          console.log("\nBatch complete:", stats);
          process.exit(0);
        })
        .catch((error) => {
          console.error("Batch failed:", error);
          process.exit(1);
        });
      break;
    }

    default:
      console.log(
        "Usage: tsx lib/fraud-scoring/signal-detectors.ts <command> [options]",
      );
      console.log("\nCommands:");
      console.log(
        "  single <entityId> [--persist]  Detect signals for a single entity",
      );
      console.log(
        "  batch [limit]                  Run detection on all charity entities (optionally limited)",
      );
      process.exit(1);
  }
}
