#!/bin/bash

# TrackFraud Disk Space Cleanup Script
# Purpose: Recover ~120GB from runaway logs while preserving important data
# Date: 2026-04-15
# Author: Generated by AI Assistant

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project root directory
PROJECT_ROOT="/Volumes/MacBackup/TrackFraudProject"
LOGS_DIR="${PROJECT_ROOT}/logs"
DATA_DIR="${PROJECT_ROOT}/data"
ARCHIVE_DIR="${PROJECT_ROOT}/archives"

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   TrackFraud Disk Space Cleanup & Recovery Script     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to display disk usage
show_disk_usage() {
    echo -e "${YELLOW}=== Current Disk Usage ===${NC}"
    du -sh "${PROJECT_ROOT}"/* 2>/dev/null | sort -hr | head -15
    echo ""
}

# Function to show log file details
show_log_details() {
    echo -e "${YELLOW}=== Log File Analysis ===${NC}"
    echo "File Size (GB)   Lines          Filename"
    echo "─────────────────────────────────────────────────────────────"

    for logfile in "${LOGS_DIR}"/*.log; do
        if [ -f "$logfile" ]; then
            filename=$(basename "$logfile")
            size_gb=$(du -sh "$logfile" 2>/dev/null | cut -f1)
            line_count=$(wc -l < "$logfile" 2>/dev/null || echo "0")

            # Format the output nicely
            printf "%-15s %-15s %s\n" "$size_gb" "$line_count" "$filename"
        fi
    done

    echo ""
}

# Function to check for running ingestion processes
check_running_processes() {
    echo -e "${YELLOW}=== Checking Running Ingestion Processes ===${NC}"

    # Check if any problematic scripts are still running
    if pgrep -f "ingest-irs-eo-bmf" > /dev/null; then
        echo -e "${RED}⚠️  WARNING: IRS BMF ingestion script is still running!${NC}"
        ps aux | grep -E "ingest-irs-eo-bmf|irs-bmf" | grep -v grep
        return 1
    else
        echo -e "${GREEN}✓ No runaway ingestion scripts detected${NC}"
        return 0
    fi
}

# Function to archive a file with compression
archive_file() {
    local source_file="$1"
    local filename=$(basename "$source_file")
    local timestamp=$(date +%Y%m%d_%H%M%S)
    local archive_name="${filename%.log}_archived_${timestamp}.gz"

    echo -e "${BLUE}Archiving: ${filename}${NC}"
    echo "  Creating compressed archive in: ${ARCHIVE_DIR}/${archive_name}"

    # Create archive directory if it doesn't exist
    mkdir -p "${ARCHIVE_DIR}/logs_$(date +%Y%m)"

    # Compress and move to archive
    gzip -c "$source_file" > "${ARCHIVE_DIR}/logs_$(date +%Y%m)/${archive_name}"

    # Remove original file
    rm "$source_file"

    echo -e "${GREEN}✓ Successfully archived ${filename}${NC}"
}

# Function to truncate log files instead of deleting (safer)
truncate_logs() {
    local keep_lines=${1:-10000}

    for logfile in "${LOGS_DIR}"/*.log; do
        if [ -f "$logfile" ]; then
            filesize=$(du -sh "$logfile" 2>/dev/null | cut -f1)
            filename=$(basename "$logfile")

            # Only truncate files larger than 100MB
            if [[ "$filesize" =~ ^[0-9]+G ]] || [[ "$filesize" == *"M"* && $(echo "$filesize" | grep -o '[0-9]*') -gt 100 ]]; then
                echo -e "${YELLOW}Truncating ${filename} (keeping last ${keep_lines} lines)${NC}"

                # Keep last N lines in a temp file, then replace
                tail -n "$keep_lines" "$logfile" > "${logfile}.tmp"
                mv "${logfile}.tmp" "$logfile"
            fi
        fi
    done
}

# Function to analyze what's causing the log spam
analyze_error_pattern() {
    local logfile="$1"
    echo -e "${YELLOW}=== Analyzing Error Pattern in ${logfile} ===${NC}"

    if [ -f "$logfile" ]; then
        # Count unique error types (last 1000 lines)
        echo "Top 10 error patterns (from last 1000 lines):"
        tail -n 1000 "$logfile" | grep -oE '\[.*?\]' | sort | uniq -c | sort -rn | head -10

        # Check for database connection errors
        db_errors=$(tail -n 1000 "$logfile" | grep -c "Can't reach database server" || echo "0")
        if [ "$db_errors" -gt 0 ]; then
            echo -e "${RED}Found ${db_errors} database connection errors in last 1000 lines${NC}"
        fi
    fi
}

# Main cleanup logic
main() {
    local mode="${1:-interactive}"

    show_disk_usage

    # Check for running processes first
    if ! check_running_processes; then
        echo -e "${RED}⚠️  Please stop the runaway ingestion script before proceeding!${NC}"
        echo "Run: docker-compose down || pkill -f ingest-irs-eo-bmf"
        exit 1
    fi

    # Create archive directory
    mkdir -p "${ARCHIVE_DIR}"

    case "$mode" in
        interactive)
            show_log_details

            echo -e "${YELLOW}=== Cleanup Options ===${NC}"
            echo "1. Archive and compress large logs (recommended)"
            echo "2. Truncate logs to last 10,000 lines only"
            echo "3. Delete all log files larger than 1GB"
            echo "4. Analyze error patterns first"
            echo "5. Show disk usage and exit"
            echo ""

            read -p "Choose an option (1-5): " choice

            case $choice in
                1)
                    echo -e "${GREEN}Archiving large log files...${NC}"

                    # Archive the problematic logs
                    archive_file "${LOGS_DIR}/irs-bmf.log"
                    archive_file "${LOGS_DIR}/corporate-ingest.log"

                    # Compress other large logs (>100MB) but don't delete originals yet
                    for logfile in "${LOGS_DIR}"/*.log; do
                        if [ -f "$logfile" ]; then
                            filesize=$(du -sh "$logfile" 2>/dev/null | cut -f1)
                            filename=$(basename "$logfile")

                            # Check if file is larger than 100MB (skip already archived ones)
                            if [[ ! "$filename" =~ "archived" ]] && [ "$(echo "$filesize" | grep -o '[0-9]*')" -gt 100 ]; then
                                echo -e "${BLUE}Compressing ${filename} for backup...${NC}"
                                gzip -k "$logfile"
                            fi
                        fi
                    done

                    ;;

                2)
                    echo -e "${YELLOW}Truncating all logs to last 10,000 lines...${NC}"
                    truncate_logs 10000
                    ;;

                3)
                    read -p "Are you sure? This will DELETE files without backup (yes/no): " confirm
                    if [ "$confirm" = "yes" ]; then
                        find "${LOGS_DIR}" -name "*.log" -size +1G -exec rm {} \;
                        echo -e "${GREEN}✓ Deleted all log files larger than 1GB${NC}"
                    else
                        echo "Operation cancelled."
                    fi
                    ;;

                4)
                    analyze_error_pattern "${LOGS_DIR}/irs-bmf.log"
                    ;;

                5)
                    show_disk_usage
                    exit 0
                    ;;

                *)
                    echo -e "${RED}Invalid option${NC}"
                    exit 1
                    ;;
            esac

            ;;

        auto)
            # Automatic cleanup mode (safest approach)
            echo -e "${GREEN}Running automatic safe cleanup...${NC}"

            # Archive the two biggest offenders
            archive_file "${LOGS_DIR}/irs-bmf.log"
            archive_file "${LOGS_DIR}/corporate-ingest.log"

            # Compress all other large logs (keep originals)
            for logfile in "${LOGS_DIR}"/*.log; do
                if [ -f "$logfile" ] && [[ ! "$(basename $logfile)" =~ "archived" ]]; then
                    gzip -k "$logfile" 2>/dev/null || true
                fi
            done

            echo -e "${GREEN}✓ Automatic cleanup complete${NC}"
            ;;

        analyze)
            # Just show analysis, no changes
            show_log_details
            analyze_error_pattern "${LOGS_DIR}/irs-bmf.log"
            ;;

        *)
            echo "Usage: $0 [interactive|auto|analyze]"
            echo ""
            echo "Modes:"
            echo "  interactive - Choose cleanup options manually (default)"
            echo "  auto        - Automatic safe cleanup with archiving"
            echo "  analyze     - Show analysis without making changes"
            exit 1
            ;;
    esac

    # Show results
    echo ""
    echo -e "${GREEN}=== Cleanup Complete ===${NC}"
    show_disk_usage

    # Calculate space recovered
    local archived_size=$(du -sh "${ARCHIVE_DIR}" 2>/dev/null | cut -f1)
    echo -e "Archives created: ${archived_size}"

    echo ""
    echo -e "${BLUE}=== Next Steps ===${NC}"
    echo "1. Verify your Docker containers are running: docker-compose ps"
    echo "2. Check database connectivity: docker-compose exec postgres psql -U trackfraud -d trackfraud -c 'SELECT 1'"
    echo "3. Review the archived logs if you need historical data"
    echo "4. Fix the root cause: The IRS BMF script was failing due to database connection issues"
    echo ""
}

# Run main function with all arguments
main "$@"
