import Link from "next/link";
import { IconScale } from "@/components/ui/Icons";

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <IconScale className="w-8 h-8 text-red-500" />
        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">
          Legal Disclaimer
        </h1>
      </div>

      <div className="prose prose-invert max-w-none space-y-6 text-gray-300 dark:text-gray-400">
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            Nature of Information
          </h2>
          <p>
            TrackFraud aggregates and displays data sourced exclusively from
            public records, government databases, regulatory filings, and other
            publicly available sources. All data presented on this platform is
            derived from these official sources and has not been independently
            verified by TrackFraud.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            Not Legal Advice
          </h2>
          <p>
            The information provided on this platform is for informational and
            research purposes only. It does not constitute legal advice, legal
            opinion, or any form of professional advice. Consult with qualified
            legal counsel before making any decisions based on information found
            on this platform.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            No Warranty
          </h2>
          <p>
            While we strive to present accurate and up-to-date information,
            TrackFraud makes no representations or warranties of any kind,
            express or implied, about the completeness, accuracy, reliability,
            suitability, or availability of the information contained on this
            platform. Any reliance you place on such information is strictly at
            your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            Risk Scores &amp; Analysis
          </h2>
          <p>
            Risk scores and analytical assessments generated by TrackFraud are
            based on algorithmic models using publicly available data. These
            scores are intended as research tools and should not be interpreted
            as definitive determinations of fraud, guilt, or wrongdoing.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            Liability Limitation
          </h2>
          <p>
            TrackFraud, its contributors, and affiliates shall not be liable for
            any direct, indirect, incidental, consequential, or punitive damages
            arising out of your access to, use of, or inability to use this
            platform or its content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            Inaccurate Data?
          </h2>
          <p>
            If you believe that information displayed on this platform is
            inaccurate, outdated, or should be removed, please use our{" "}
            <Link
              href="/contact/takedown"
              className="text-red-500 hover:text-red-400 underline"
            >
              takedown process
            </Link>{" "}
            to request a review. We aim to respond to valid takedown requests
            within 48 business hours.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">
            Source Attribution
          </h2>
          <p>
            We make efforts to attribute data to its original source. Each data
            point on our platform references the government agency or public
            database from which it was obtained. These sources remain the
            authoritative record.
          </p>
        </section>

        <div className="pt-4 border-t border-gray-800">
          <p className="text-sm text-gray-500">
            Last updated: May 2025. This disclaimer may be updated periodically.
          </p>
        </div>
      </div>
    </div>
  );
}
